import { Car } from "@/domain/Car";

let demoCars: Car[] = [
    {
        carId: 1,
        name: "Tesla Roadster",
        price: 500,
        kilometers: 30,
        transmission: "Automatic",
        fuelType: "Electric",
    },
    {
        carId: 2,
        name: "Lamborghini Huracán",
        price: 1200,
        kilometers: 10,
        transmission: "Automatic",
        fuelType: "Gasoline",
    },
    {
        carId: 3,
        name: "Porsche 911 Carrera",
        price: 900,
        kilometers: 50,
        transmission: "Manual",
        fuelType: "Gasoline",
    },
    {
        carId: 4,
        name: "Ferrari F8 Tributo",
        price: 150,
        kilometers: 20,
        transmission: "Automatic",
        fuelType: "Gasoline",
    },
    {
        carId: 5,
        name: "McLaren 720S",
        price: 140,
        kilometers: 25,
        transmission: "Automatic",
        fuelType: "Gasoline",
    },
    {
        carId: 6,
        name: "BMW i8",
        price: 750,
        kilometers: 60,
        transmission: "Automatic",
        fuelType: "Hybrid",
    },
    {
        carId: 7,
        name: "Audi R8",
        price: 110,
        kilometers: 40,
        transmission: "Automatic",
        fuelType: "Gasoline",
    },
    {
        carId: 8,
        name: "Mercedes-AMG GT",
        price: 100,
        kilometers: 50,
        transmission: "Automatic",
        fuelType: "Gasoline",
    },
    {
        carId: 9,
        name: "Bugatti Chiron",
        price: 250,
        kilometers: 15,
        transmission: "Automatic",
        fuelType: "Gasoline",
    },
    {
        carId: 10,
        name: "Koenigsegg Jesko",
        price: 300,
        kilometers: 5,
        transmission: "Automatic",
        fuelType: "Gasoline",
    },
    {
        carId: 11,
        name: "Lucid Air Dream Edition",
        price: 850,
        kilometers: 100,
        transmission: "Automatic",
        fuelType: "Electric",
    },
    {
        carId: 12,
        name: "Rolls-Royce Ghost",
        price: 200,
        kilometers: 80,
        transmission: "Automatic",
        fuelType: "Gasoline",
    },
];

export { demoCars };
